version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-container
    ports:
      - "11434:11434" # Порт для Ollama API
    volumes:
      - ./models:/models  # Локальная папка для хранения моделей
      - ./entrypoint.sh:/entrypoint.sh
    pull_policy: always
    tty: true
    restart: always
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]

  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mongo:
      image: mongo:6.0
      container_name: mongo-container
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      restart: always

  redis:
      image: redis:7-alpine
      container_name: redis-container
      ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
      environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
      volumes:
        - redis_data:/data
      restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
          - ./app/config:/config
    depends_on:
      - ollama
      - redis
      - postgres
      - mongo

volumes:
    postgres_data:
    mongo_data:
    redis_data: